//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Task
    {
        public int ID { get; set; }
        public string strTitle { get; set; }
        public string strDescripition { get; set; }
        public Nullable<System.DateTime> dtDueDate { get; set; }
        public int requiredHours { get; set; }
        public Nullable<int> priority { get; set; }
    }
}
